dataset: SKIN40
first_split_size: 5
other_split_size: 5
schedule:
- 5
schedule_type: cosine
batch_size: 16
optimizer: Adam
lr: 0.001
momentum: 0.9
weight_decay: 0
model_type: zoo
model_name: vit_pt_imnet
max_task: -1
dataroot: data
workers: 4
validation: False
train_aug: True
rand_split: True
save_distribution: 0 # if use feature aug. 0:not aug;1:aug;2:aug2;3:merge;4:random choose;5:kmeans